<?php
/**
 * Safe UTF-8 DB Exporter
 * รัน: php scripts/export_db_safe.php > /dev/null (ไฟล์จะอยู่ที่ scripts/dump_safe.sql)
 * หรือ: C:\xampp\php\php.exe scripts\export_db_safe.php
 */
$cfg = require __DIR__ . '/../app/Config/database.php';

$pdo = new PDO(
    "mysql:host={$cfg['host']};port={$cfg['port']};dbname={$cfg['database']};charset=utf8mb4",
    $cfg['username'], $cfg['password'],
    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
);

$outFile = __DIR__ . '/dump_safe.sql';
$fh = fopen($outFile, 'w');

fwrite($fh, "-- Safe UTF-8 dump generated by export_db_safe.php\n");
fwrite($fh, "-- " . date('Y-m-d H:i:s') . "\n\n");
fwrite($fh, "SET NAMES utf8mb4;\n");
fwrite($fh, "SET FOREIGN_KEY_CHECKS=0;\n\n");

$tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);

foreach ($tables as $table) {
    echo "Exporting: $table\n";

    // truncate
    fwrite($fh, "TRUNCATE TABLE `$table`;\n");

    $rows = $pdo->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
    if (empty($rows)) continue;

    $cols = '`' . implode('`, `', array_keys($rows[0])) . '`';

    foreach (array_chunk($rows, 100) as $chunk) {
        $values = [];
        foreach ($chunk as $row) {
            $vals = array_map(function ($v) use ($pdo) {
                if ($v === null) return 'NULL';
                return $pdo->quote($v);
            }, array_values($row));
            $values[] = '(' . implode(', ', $vals) . ')';
        }
        fwrite($fh, "INSERT INTO `$table` ($cols) VALUES\n" . implode(",\n", $values) . ";\n");
    }
    fwrite($fh, "\n");
}

fwrite($fh, "SET FOREIGN_KEY_CHECKS=1;\n");
fclose($fh);
echo "\nDone! Output: $outFile\n";
